backend:
  replicaCount: 4


frontend:
  replicaCount: 4

ingress:
  host: llm-monitor.local

# secrets configuration

secrets:
  supabaseUrl: ""
  supabaseServiceKey: ""
  supabaseAnonKey: ""
  secretKey: ""