apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.backend.replicaCount }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          ports:
            - containerPort: 8000

          env:
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SUPABASE_URL

            - name: SUPABASE_SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SUPABASE_SERVICE_KEY

            - name: SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SUPABASE_ANON_KEY

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SECRET_KEY

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"